/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WabliWimage from './WabliWimage';

/**
 * The Wabli model module.
 * @module model/Wabli
 * @version 1.0.0
 */
class Wabli {
    /**
     * Constructs a new <code>Wabli</code>.
     * @alias module:model/Wabli
     * @param wimage {module:model/WabliWimage} 
     * @param wtitle {String} 
     */
    constructor(wimage, wtitle) { 
        
        Wabli.initialize(this, wimage, wtitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wimage, wtitle) { 
        obj['wimage'] = wimage;
        obj['wtitle'] = wtitle;
    }

    /**
     * Constructs a <code>Wabli</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Wabli} obj Optional instance to populate.
     * @return {module:model/Wabli} The populated <code>Wabli</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Wabli();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('wimage')) {
                obj['wimage'] = WabliWimage.constructFromObject(data['wimage']);
            }
            if (data.hasOwnProperty('wtitle')) {
                obj['wtitle'] = ApiClient.convertToType(data['wtitle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Wabli.prototype['_id'] = undefined;

/**
 * @member {module:model/WabliWimage} wimage
 */
Wabli.prototype['wimage'] = undefined;

/**
 * @member {String} wtitle
 */
Wabli.prototype['wtitle'] = undefined;






export default Wabli;

